version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: userpostgres
      POSTGRES_PASSWORD: userpostgres  
      POSTGRES_DB: userpostgres                  
    volumes:
      - ./Bdd/CreationTable.sql:/docker-entrypoint-initdb.d/01-CreationTable.sql
      - ./Bdd/insert_villes.sql:/docker-entrypoint-initdb.d/02-insert_villes.sql
    ports:
      - "5433:5432"  # Port 5433 sur l'hôte, 5432 dans le conteneur
  api:
    build: .  # Utilise le Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=userpostgres
      - DB_PASSWORD=userpostgres  
      - DB_NAME=userpostgres                
      - DB_PORT=5432                  # Port interne au conteneur
    ports:
      - "3001:3001"  # Ajuste selon le port de ton API (ex. 8080 si différent)