version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: userpostgres
      POSTGRES_PASSWORD: userpostgres  
      POSTGRES_DB: userpostgres                  
    volumes:
      - db_data:/var/lib/postgresql/data 
      - ./Bdd/CreationTable.sql:/docker-entrypoint-initdb.d/01-CreationTable.sql
      - ./Bdd/insert_villes.sql:/docker-entrypoint-initdb.d/02-insert_villes.sql
      - ./Bdd/insert_comptes_et_annonces.sql:/docker-entrypoint-initdb.d/03-insert_comptes_et_annonces.sql
    ports:
      - "5432:5432"  # Port 5433 sur l'hôte, 5432 dans le conteneur
  api:
    build: .
    depends_on:
      - db
    volumes:
      - ./server:/app/server
      - ./old-public:/app/old-public
      - ./.env:/app/.env
      - /app/node_modules
      - ./public/public/images:/app/public/images
    environment:
      - DB_HOST=db
      - DB_USER=userpostgres
      - DB_PASSWORD=userpostgres  
      - DB_NAME=userpostgres                
      - DB_PORT=5432
    ports:
      - "3001:3001"

# Définition du volume PERSISTANT (obligatoire)
volumes:
  db_data:  